INSERT INTO categories (name, description) VALUES ('Reklamacje', 'pisma wysyłane w sprawie reklamacji');
INSERT INTO categories (name, description) VALUES ('Klienci', 'pisma wysyłane do klientów');
INSERT INTO categories (name, description) VALUES ('Administracyjne', 'pisma wewnętrzne administracyjne');
INSERT INTO categories (name, description) VALUES ('HR', 'pisma wysyłane do działu zasobów ludzkich');
INSERT INTO categories (name, description) VALUES ('Logistyka', 'pisma wysyłane do działu logistyki');
INSERT INTO categories (name, description) VALUES ('Marketing', 'pisma wysyłane do działu marketingu');
INSERT INTO categories (name, description) VALUES ('Sprzedaż', 'pisma wysyłane do działu sprzedaży');
INSERT INTO categories (name, description) VALUES ('Techniczne', 'pisma wysyłane do działu technicznego');
INSERT INTO categories (name, description) VALUES ('IT', 'pisma wysyłane do działu IT');
INSERT INTO categories (name, description) VALUES ('Kadra Zarządzająca', 'pisma wysyłane do kadry zarządzającej');
INSERT INTO categories (name, description) VALUES ('PR', 'pisma wysyłane do działu public relations');
INSERT INTO categories (name, description) VALUES ('Obsługa Klienta', 'pisma wysyłane do działu obsługi klienta');
INSERT INTO categories (name, description) VALUES ('Rachunkowość', 'pisma wysyłane do działu rachunkowości');
INSERT INTO categories (name, description) VALUES ('Zamówienia', 'pisma dotyczące zamówień');
INSERT INTO categories (name, description) VALUES ('Zakupy', 'pisma wysyłane do działu zakupów');
INSERT INTO categories (name, description) VALUES ('Rekrutacja', 'pisma dotyczące rekrutacji');
INSERT INTO categories (name, description) VALUES ('Szkolenia', 'pisma dotyczące szkoleń');
INSERT INTO categories (name, description) VALUES ('Prawne', 'pisma wysyłane do działu prawnego');
INSERT INTO categories (name, description) VALUES ('Bezpieczeństwo', 'pisma dotyczące bezpieczeństwa');
INSERT INTO categories (name, description) VALUES ('Higiena Pracy', 'pisma dotyczące higieny pracy');
INSERT INTO categories (name, description) VALUES ('Projekty', 'pisma dotyczące projektów');
INSERT INTO categories (name, description) VALUES ('Konsultacje', 'pisma dotyczące konsultacji');
INSERT INTO categories (name, description) VALUES ('Audyt', 'pisma wysyłane do działu audytu');
INSERT INTO categories (name, description) VALUES ('Zarządzanie', 'pisma dotyczące zarządzania');
INSERT INTO categories (name, description) VALUES ('Strategia', 'pisma dotyczące strategii');
INSERT INTO categories (name, description) VALUES ('Rozwój', 'pisma dotyczące rozwoju');
INSERT INTO categories (name, description) VALUES ('Finanse', 'pisma dotyczące finansów');
INSERT INTO categories (name, description) VALUES ('Analizy', 'pisma dotyczące analiz');
INSERT INTO categories (name, description) VALUES ('Badania', 'pisma dotyczące badań');
INSERT INTO categories (name, description) VALUES ('Kontrola', 'pisma dotyczące kontroli');
INSERT INTO categories (name, description) VALUES ('Innowacje', 'pisma dotyczące innowacji');
INSERT INTO categories (name, description) VALUES ('Zrównoważony Rozwój', 'pisma dotyczące zrównoważonego rozwoju');
INSERT INTO categories (name, description) VALUES ('CSR', 'pisma dotyczące społecznej odpowiedzialności biznesu');
INSERT INTO categories (name, description) VALUES ('E-commerce', 'pisma dotyczące e-commerce');
INSERT INTO categories (name, description) VALUES ('Transport', 'pisma dotyczące transportu');
INSERT INTO categories (name, description) VALUES ('Magazynowanie', 'pisma dotyczące magazynowania');
INSERT INTO categories (name, description) VALUES ('Dystrybucja', 'pisma dotyczące dystrybucji');
INSERT INTO categories (name, description) VALUES ('Produkcja', 'pisma dotyczące produkcji');
INSERT INTO categories (name, description) VALUES ('Jakość', 'pisma dotyczące kontroli jakości');
INSERT INTO categories (name, description) VALUES ('Ochrona Środowiska', 'pisma dotyczące ochrony środowiska');
INSERT INTO categories (name, description) VALUES ('Zasoby', 'pisma dotyczące zarządzania zasobami');
INSERT INTO categories (name, description) VALUES ('Planowanie', 'pisma dotyczące planowania');
INSERT INTO categories (name, description) VALUES ('Harmonogramy', 'pisma dotyczące harmonogramów');
INSERT INTO categories (name, description) VALUES ('Sprawozdania', 'pisma dotyczące sprawozdań');
INSERT INTO categories (name, description) VALUES ('Raporty', 'pisma dotyczące raportów');
INSERT INTO categories (name, description) VALUES ('Dokumentacja', 'pisma dotyczące dokumentacji');
INSERT INTO categories (name, description) VALUES ('Archiwizacja', 'pisma dotyczące archiwizacji');
INSERT INTO categories (name, description) VALUES ('Kontakt z Klientem', 'pisma dotyczące kontaktów z klientem');
INSERT INTO categories (name, description) VALUES ('Umowy', 'pisma dotyczące umów');
INSERT INTO categories (name, description) VALUES ('Kontrakty', 'pisma dotyczące kontraktów');
INSERT INTO categories (name, description) VALUES ('Negocjacje', 'pisma dotyczące negocjacji');
INSERT INTO categories (name, description) VALUES ('Partnerstwa', 'pisma dotyczące partnerstw');
INSERT INTO categories (name, description) VALUES ('Alianse', 'pisma dotyczące aliansów');
INSERT INTO categories (name, description) VALUES ('Protokół', 'pisma dotyczące protokołów');
INSERT INTO categories (name, description) VALUES ('Zarządzenia', 'pisma dotyczące zarządzeń');
INSERT INTO categories (name, description) VALUES ('Decyzje', 'pisma dotyczące decyzji');
INSERT INTO categories (name, description) VALUES ('Postanowienia', 'pisma dotyczące postanowień');
INSERT INTO categories (name, description) VALUES ('Oświadczenia', 'pisma dotyczące oświadczeń');
INSERT INTO categories (name, description) VALUES ('Instrukcje', 'pisma dotyczące instrukcji');
INSERT INTO categories (name, description) VALUES ('Zawiadomienia', 'pisma dotyczące zawiadomień');
INSERT INTO categories (name, description) VALUES ('Noty', 'pisma dotyczące not');
INSERT INTO categories (name, description) VALUES ('Wezwania', 'pisma dotyczące wezwań');
INSERT INTO categories (name, description) VALUES ('Przypomnienia', 'pisma dotyczące przypomnień');
INSERT INTO categories (name, description) VALUES ('Zaproszenia', 'pisma dotyczące zaproszeń');
INSERT INTO categories (name, description) VALUES ('Powiadomienia', 'pisma dotyczące powiadomień');
INSERT INTO categories (name, description) VALUES ('Ogłoszenia', 'pisma dotyczące ogłoszeń');
INSERT INTO categories (name, description) VALUES ('Rejestracje', 'pisma dotyczące rejestracji');
INSERT INTO categories (name, description) VALUES ('Certyfikaty', 'pisma dotyczące certyfikatów');
INSERT INTO categories (name, description) VALUES ('Licencje', 'pisma dotyczące licencji');
INSERT INTO categories (name, description) VALUES ('Zezwolenia', 'pisma dotyczące zezwoleń');
INSERT INTO categories (name, description) VALUES ('Aprobata', 'pisma dotyczące aprobaty');
INSERT INTO categories (name, description) VALUES ('Rekomendacje', 'pisma dotyczące rekomendacji');
INSERT INTO categories (name, description) VALUES ('Referencje', 'pisma dotyczące referencji');
INSERT INTO categories (name, description) VALUES ('Potwierdzenia', 'pisma dotyczące potwierdzeń');
INSERT INTO categories (name, description) VALUES ('Prośby', 'pisma dotyczące próśb');
INSERT INTO categories (name, description) VALUES ('Zapytania', 'pisma dotyczące zapytań');
INSERT INTO categories (name, description) VALUES ('Interpelacje', 'pisma dotyczące interpelacji');
INSERT INTO categories (name, description) VALUES ('Wnioski', 'pisma dotyczące wniosków');
INSERT INTO categories (name, description) VALUES ('Propozycje', 'pisma dotyczące propozycji');
INSERT INTO categories (name, description) VALUES ('Oferty', 'pisma dotyczące ofert');
INSERT INTO categories (name, description) VALUES ('Konsultacje Społeczne', 'pisma dotyczące konsultacji społecznych');
INSERT INTO categories (name, description) VALUES ('Planowanie Strategiczne', 'pisma dotyczące planowania strategicznego');
INSERT INTO categories (name, description) VALUES ('Zarządzanie Projektami', 'pisma dotyczące zarządzania projektami');
INSERT INTO categories (name, description) VALUES ('Dostawcy', 'pisma wysyłane do dostawców');
INSERT INTO categories (name, description) VALUES ('Klienci', 'pisma wysyłane do klientów kancelarii');
INSERT INTO categories (name, description) VALUES ('Sąd', 'pisma wysyłane do sądu');
INSERT INTO categories (name, description) VALUES ('Komornik', 'pisma wysyłane do komornika');
INSERT INTO categories (name, description) VALUES ('Policja', 'pisma wysyłane do policji');
INSERT INTO categories (name, description) VALUES ('Prokuratura', 'pisma wysyłane do prokuratury');
INSERT INTO categories (name, description) VALUES ('Urząd Skarbowy', 'pisma wysyłane do urzędu skarbowego');
INSERT INTO categories (name, description) VALUES ('ZUS', 'pisma wysyłane do Zakładu Ubezpieczeń Społecznych');
INSERT INTO categories (name, description) VALUES ('Banki', 'pisma wysyłane do banków');
INSERT INTO categories (name, description) VALUES ('Ubezpieczyciele', 'pisma wysyłane do firm ubezpieczeniowych');
INSERT INTO categories (name, description) VALUES ('Partnerzy Biznesowi', 'pisma wysyłane do partnerów biznesowych');
INSERT INTO categories (name, description) VALUES ('Podwykonawcy', 'pisma wysyłane do podwykonawców');
INSERT INTO categories (name, description) VALUES ('Organy Rządowe', 'pisma wysyłane do organów rządowych');
INSERT INTO categories (name, description) VALUES ('NGO', 'pisma wysyłane do organizacji pozarządowych');
INSERT INTO categories (name, description) VALUES ('Instytucje Finansowe', 'pisma wysyłane do instytucji finansowych');
INSERT INTO categories (name, description) VALUES ('Media', 'pisma wysyłane do mediów');
INSERT INTO categories (name, description) VALUES ('Agencje Marketingowe', 'pisma wysyłane do agencji marketingowych');
INSERT INTO categories (name, description) VALUES ('Konsultanci', 'pisma wysyłane do konsultantów');
INSERT INTO categories (name, description) VALUES ('Eksperci Branżowi', 'pisma wysyłane do ekspertów branżowych');
INSERT INTO categories (name, description) VALUES ('Usługi Serwisowe', 'pisma wysyłane do firm świadczących usługi serwisowe');
INSERT INTO categories (name, description) VALUES ('Placówki Edukacyjne', 'pisma wysyłane do placówek edukacyjnych');
INSERT INTO categories (name, description) VALUES ('Placówki Medyczne', 'pisma wysyłane do placówek medycznych');
INSERT INTO categories (name, description) VALUES ('Audytorzy Zewnętrzni', 'pisma wysyłane do audytorów zewnętrznych');
INSERT INTO categories (name, description) VALUES ('Biura Prawne', 'pisma wysyłane do innych biur prawnych');
INSERT INTO categories (name, description) VALUES ('Firmy Doradcze', 'pisma wysyłane do firm doradczych');
INSERT INTO categories (name, description) VALUES ('Centra Badawcze', 'pisma wysyłane do centrów badawczych');
INSERT INTO categories (name, description) VALUES ('Firmy Kurierskie', 'pisma wysyłane do firm kurierskich');
INSERT INTO categories (name, description) VALUES ('Organy Regulacyjne', 'pisma wysyłane do organów regulacyjnych');
INSERT INTO categories (name, description) VALUES ('Izby Handlowe', 'pisma wysyłane do izb handlowych');
INSERT INTO categories (name, description) VALUES ('Firmy Reklamowe', 'pisma wysyłane do firm reklamowych');
INSERT INTO categories (name, description) VALUES ('Instytuty Badawcze', 'pisma wysyłane do instytutów badawczych');
INSERT INTO categories (name, description) VALUES ('Stowarzyszenia Branżowe', 'pisma wysyłane do stowarzyszeń branżowych');
INSERT INTO categories (name, description) VALUES ('Firmy Sprzątające', 'pisma wysyłane do firm sprzątających');
INSERT INTO categories (name, description) VALUES ('Firmy Cateringowe', 'pisma wysyłane do firm cateringowych');
INSERT INTO categories (name, description) VALUES ('Firmy Eventowe', 'pisma wysyłane do firm eventowych');
INSERT INTO categories (name, description) VALUES ('Biura Podróży', 'pisma wysyłane do biur podróży');
INSERT INTO categories (name, description) VALUES ('Hotele', 'pisma wysyłane do hoteli');
INSERT INTO categories (name, description) VALUES ('Firmy Logistyczne', 'pisma wysyłane do firm logistycznych');
INSERT INTO categories (name, description) VALUES ('Operatorzy Telekomunikacyjni', 'pisma wysyłane do operatorów telekomunikacyjnych');
INSERT INTO categories (name, description) VALUES ('Operatorzy Internetowi', 'pisma wysyłane do operatorów internetowych');
INSERT INTO categories (name, description) VALUES ('Firmy Rekrutacyjne', 'pisma wysyłane do firm rekrutacyjnych');
INSERT INTO categories (name, description) VALUES ('Firmy Szkoleniowe', 'pisma wysyłane do firm szkoleniowych');
INSERT INTO categories (name, description) VALUES ('Targi Branżowe', 'pisma wysyłane do organizatorów targów branżowych');
INSERT INTO categories (name, description) VALUES ('Biura Tłumaczeń', 'pisma wysyłane do biur tłumaczeń');
INSERT INTO categories (name, description) VALUES ('Laboratoria', 'pisma wysyłane do laboratoriów');
INSERT INTO categories (name, description) VALUES ('Firmy IT', 'pisma wysyłane do firm IT');
INSERT INTO categories (name, description) VALUES ('Firmy HR', 'pisma wysyłane do firm HR');
INSERT INTO categories (name, description) VALUES ('Organizacje Międzynarodowe', 'pisma wysyłane do organizacji międzynarodowych');
INSERT INTO categories (name, description) VALUES ('Placówki Kultury', 'pisma wysyłane do placówek kultury');
INSERT INTO categories (name, description) VALUES ('Fundacje', 'pisma wysyłane do fundacji');
INSERT INTO categories (name, description) VALUES ('Agencje Rządowe', 'pisma wysyłane do agencji rządowych');
INSERT INTO categories (name, description) VALUES ('Organy Ścigania', 'pisma wysyłane do organów ścigania');
INSERT INTO categories (name, description) VALUES ('Firmy Zewnętrzne', 'pisma wysyłane do firm zewnętrznych');
INSERT INTO categories (name, description) VALUES ('Kancelarie Notarialne', 'pisma wysyłane do kancelarii notarialnych');
INSERT INTO categories (name, description) VALUES ('Rzecznicy Prawni', 'pisma wysyłane do rzeczników prawnych');
INSERT INTO categories (name, description) VALUES ('Urzędy Miasta', 'pisma wysyłane do urzędów miasta');
INSERT INTO categories (name, description) VALUES ('Urzędy Wojewódzkie', 'pisma wysyłane do urzędów wojewódzkich');
INSERT INTO categories (name, description) VALUES ('Ambasady', 'pisma wysyłane do ambasad');
INSERT INTO categories (name, description) VALUES ('Konsulaty', 'pisma wysyłane do konsulatów');
INSERT INTO categories (name, description) VALUES ('Instytucje Międzynarodowe', 'pisma wysyłane do instytucji międzynarodowych');
INSERT INTO categories (name, description) VALUES ('Szkoły', 'pisma wysyłane do szkół');
INSERT INTO categories (name, description) VALUES ('Uniwersytety', 'pisma wysyłane do uniwersytetów');
INSERT INTO categories (name, description) VALUES ('Firmy Budowlane', 'pisma wysyłane do firm budowlanych');
INSERT INTO categories (name, description) VALUES ('Inspektorzy', 'pisma wysyłane do inspektorów');
INSERT INTO categories (name, description) VALUES ('Właściciele Nieruchomości', 'pisma wysyłane do właścicieli nieruchomości');
INSERT INTO categories (name, description) VALUES ('Firmy Transportowe', 'pisma wysyłane do firm transportowych');
INSERT INTO categories (name, description) VALUES ('Brokerzy', 'pisma wysyłane do brokerów');
INSERT INTO categories (name, description) VALUES ('Organizatorzy Wydarzeń', 'pisma wysyłane do organizatorów wydarzeń');
INSERT INTO categories (name, description) VALUES ('Specjaliści ds. Bezpieczeństwa', 'pisma wysyłane do specjalistów ds. bezpieczeństwa');
INSERT INTO categories (name, description) VALUES ('Firmy Księgowe', 'pisma wysyłane do firm księgowych');
INSERT INTO categories (name, description) VALUES ('Agencje Reklamowe', 'pisma wysyłane do agencji reklamowych');
INSERT INTO categories (name, description) VALUES ('Firmy Sprzętowe', 'pisma wysyłane do firm sprzętowych');
INSERT INTO categories (name, description) VALUES ('Firmy Przemysłowe', 'pisma wysyłane do firm przemysłowych');
INSERT INTO categories (name, description) VALUES ('Firmy Produkcyjne', 'pisma wysyłane do firm produkcyjnych');
INSERT INTO categories (name, description) VALUES ('Firmy Handlowe', 'pisma wysyłane do firm handlowych');
INSERT INTO categories (name, description) VALUES ('Firmy Zarządzające Nieruchomościami', 'pisma wysyłane do firm zarządzających nieruchomościami');
INSERT INTO categories (name, description) VALUES ('Firmy Energetyczne', 'pisma wysyłane do firm energetycznych');
INSERT INTO categories (name, description) VALUES ('Firmy Wodociągowe', 'pisma wysyłane do firm wodociągowych');
INSERT INTO categories (name, description) VALUES ('Firmy Gazownicze', 'pisma wysyłane do firm gazowniczych');
INSERT INTO categories (name, description) VALUES ('Firmy Usługowe', 'pisma wysyłane do firm usługowych');
INSERT INTO categories (name, description) VALUES ('Przedsiębiorstwa Komunalne', 'pisma wysyłane do przedsiębiorstw komunalnych');
INSERT INTO categories (name, description) VALUES ('Organy Nadzoru', 'pisma wysyłane do organów nadzoru');
INSERT INTO categories (name, description) VALUES ('Firmy Audytorskie', 'pisma wysyłane do firm audytorskich');
INSERT INTO categories (name, description) VALUES ('Firmy Consultingowe', 'pisma wysyłane do firm consultingowych');
INSERT INTO categories (name, description) VALUES ('Agencje Zatrudnienia', 'pisma wysyłane do agencji zatrudnienia');
INSERT INTO categories (name, description) VALUES ('Organizacje Związkowe', 'pisma wysyłane do organizacji związkowych');
INSERT INTO categories (name, description) VALUES ('Fundusze Emerytalne', 'pisma wysyłane do funduszy emerytalnych');
INSERT INTO categories (name, description) VALUES ('Agencje Nieruchomości', 'pisma wysyłane do agencji nieruchomości');
INSERT INTO categories (name, description) VALUES ('Rady Miasta', 'pisma wysyłane do rad miast');
INSERT INTO categories (name, description) VALUES ('Powiaty', 'pisma wysyłane do powiatów');
INSERT INTO categories (name, description) VALUES ('Gminy', 'pisma wysyłane do gmin');
INSERT INTO categories (name, description) VALUES ('Starostwa', 'pisma wysyłane do starostw');
INSERT INTO categories (name, description) VALUES ('Organizacje Ekologiczne', 'pisma wysyłane do organizacji ekologicznych');
INSERT INTO categories (name, description) VALUES ('Organizacje Charytatywne', 'pisma wysyłane do organizacji charytatywnych');
INSERT INTO categories (name, description) VALUES ('Społeczności Lokalnej', 'pisma wysyłane do społeczności lokalnych');
INSERT INTO categories (name, description) VALUES ('Instytucje Ochrony Zdrowia', 'pisma wysyłane do instytucji ochrony zdrowia');
INSERT INTO categories (name, description) VALUES ('Zakłady Pracy', 'pisma wysyłane do zakładów pracy');
INSERT INTO categories (name, description) VALUES ('Firmy Recyklingowe', 'pisma wysyłane do firm recyklingowych');
INSERT INTO categories (name, description) VALUES ('Deweloperzy', 'pisma wysyłane do deweloperów');
INSERT INTO categories (name, description) VALUES ('Firmy Architektoniczne', 'pisma wysyłane do firm architektonicznych');
INSERT INTO categories (name, description) VALUES ('Firmy Geodezyjne', 'pisma wysyłane do firm geodezyjnych');
INSERT INTO categories (name, description) VALUES ('Firmy Inżynieryjne', 'pisma wysyłane do firm inżynieryjnych');
INSERT INTO categories (name, description) VALUES ('Firmy Projektowe', 'pisma wysyłane do firm projektowych');
INSERT INTO categories (name, description) VALUES ('Firmy Instalacyjne', 'pisma wysyłane do firm instalacyjnych');
INSERT INTO categories (name, description) VALUES ('Firmy Remontowe', 'pisma wysyłane do firm remontowych');
INSERT INTO categories (name, description) VALUES ('Operatorzy Kolejowi', 'pisma wysyłane do operatorów kolejowych');
INSERT INTO categories (name, description) VALUES ('Linie Lotnicze', 'pisma wysyłane do linii lotniczych');
INSERT INTO categories (name, description) VALUES ('Firmy Spedycyjne', 'pisma wysyłane do firm spedycyjnych');
INSERT INTO categories (name, description) VALUES ('Firmy Ciepłownicze', 'pisma wysyłane do firm ciepłowniczych');
INSERT INTO categories (name, description) VALUES ('Firmy Informatyczne', 'pisma wysyłane do firm informatycznych');
INSERT INTO categories (name, description) VALUES ('Firmy Telekomunikacyjne', 'pisma wysyłane do firm telekomunikacyjnych');
INSERT INTO categories (name, description) VALUES ('Firmy Graficzne', 'pisma wysyłane do firm graficznych');
INSERT INTO categories (name, description) VALUES ('Biura Rachunkowe', 'pisma wysyłane do biur rachunkowych');
INSERT INTO categories (name, description) VALUES ('Firmy Księgowe', 'pisma wysyłane do firm księgowych');
INSERT INTO categories (name, description) VALUES ('Firmy Sprzętowe', 'pisma wysyłane do firm sprzętowych');
INSERT INTO categories (name, description) VALUES ('Firmy Produkcyjne', 'pisma wysyłane do firm produkcyjnych');
INSERT INTO categories (name, description) VALUES ('Firmy Energetyczne', 'pisma wysyłane do firm energetycznych');
INSERT INTO categories (name, description) VALUES ('Firmy Wodociągowe', 'pisma wysyłane do firm wodociągowych');
INSERT INTO categories (name, description) VALUES ('Firmy Gazownicze', 'pisma wysyłane do firm gazowniczych');
INSERT INTO categories (name, description) VALUES ('Firmy Usługowe', 'pisma wysyłane do firm usługowych');
INSERT INTO categories (name, description) VALUES ('Przedsiębiorstwa Komunalne', 'pisma wysyłane do przedsiębiorstw komunalnych');
INSERT INTO categories (name, description) VALUES ('Firmy Budowlane', 'pisma wysyłane do firm budowlanych');
INSERT INTO categories (name, description) VALUES ('Firmy Ochroniarskie', 'pisma wysyłane do firm ochroniarskich');
INSERT INTO categories (name, description) VALUES ('Operatorzy Sieci Komórkowych', 'pisma wysyłane do operatorów sieci komórkowych');
INSERT INTO categories (name, description) VALUES ('Firmy Organizujące Konferencje', 'pisma wysyłane do firm organizujących konferencje');
INSERT INTO categories (name, description) VALUES ('Urzędy Marszałkowskie', 'pisma wysyłane do urzędów marszałkowskich');
INSERT INTO categories (name, description) VALUES ('Izby Rzemieślnicze', 'pisma wysyłane do izb rzemieślniczych');
INSERT INTO categories (name, description) VALUES ('Izby Przemysłowe', 'pisma wysyłane do izb przemysłowych');
INSERT INTO categories (name, description) VALUES ('Firmy Zarządzające Nieruchomościami', 'pisma wysyłane do firm zarządzających nieruchomościami');
INSERT INTO categories (name, description) VALUES ('Firmy Wynajmujące Sprzęt', 'pisma wysyłane do firm wynajmujących sprzęt');
INSERT INTO categories (name, description) VALUES ('Firmy Handlowe', 'pisma wysyłane do firm handlowych');
INSERT INTO categories (name, description) VALUES ('Firmy Dystrybucyjne', 'pisma wysyłane do firm dystrybucyjnych');
INSERT INTO categories (name, description) VALUES ('Firmy Usługowe', 'pisma wysyłane do firm usługowych');
INSERT INTO categories (name, description) VALUES ('Przedsiębiorstwa Komunalne', 'pisma wysyłane do przedsiębiorstw komunalnych');

